# Generated by Django 5.2.7 on 2025-10-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformasiPertandingan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informasi',
            name='country',
            field=models.CharField(default='Indonesia', max_length=100),
        ),
    ]
