# Generated by Django 5.2.7 on 2025-10-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformasiPertandingan', '0002_informasi_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informasi',
            name='country',
            field=models.CharField(max_length=100),
        ),
    ]
