# Generated by Django 5.2.7 on 2025-10-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumApp', '0003_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
