# Generated by Django 5.2.7 on 2025-10-22 14:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('training_jersey', 'Training Jersey'), ('socks', 'Socks'), ('ball', 'Ball'), ('accessory', 'Accessory'), ('tops', 'Tops'), ('others', 'Others')], max_length=100)),
                ('stock', models.IntegerField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('product_views', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('purchased_at', models.DateField(default=django.utils.timezone.localdate)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reviewproduct.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewproduct.merchandise')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('body', models.TextField()),
                ('purchased_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviewproduct.merchandise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'deleted', '-created_at'], name='reviewprodu_product_a9010a_idx'), models.Index(fields=['product', 'rating'], name='reviewprodu_product_6ac293_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'user'), name='unique_user_review_per_product')],
            },
        ),
    ]
