# Generated by Django 5.2.7 on 2025-10-23 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandiseApp', '0001_initial'),
        ('reviewproduct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchandiseApp.merchandise'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='merchandiseApp.merchandise'),
        ),
        migrations.DeleteModel(
            name='Merchandise',
        ),
    ]
