# Generated by Django 5.2.7 on 2025-10-24 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewproduct', '0002_alter_orderitem_product_alter_review_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
