# Generated by Django 5.2.7 on 2025-10-26 02:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandiseApp', '0002_alter_merchandise_user'),
        ('reviewproduct', '0003_remove_orderitem_order_remove_orderitem_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_user_review_per_product',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('product', 'user'), name='unique_user_review_per_product_active'),
        ),
    ]
