# Generated by Django 5.2.7 on 2025-10-22 15:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('training jersey', 'Training Jersey'), ('socks', 'Socks'), ('ball', 'Ball'), ('accessory', 'Accessory'), ('tops', 'Tops'), ('others', 'Others')], max_length=100)),
                ('variants', models.JSONField(blank=True, null=True)),
                ('sold_count', models.IntegerField(default=0)),
                ('rating_count', models.IntegerField(default=0)),
                ('rating_avg', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('notes', models.TextField(blank=True, default='')),
                ('payment_method', models.CharField(choices=[('ewallet_gopay', 'Ewallet - GoPay'), ('ewallet_ovo', 'Ewallet - OVO'), ('ewallet_flip', 'Ewallet - Flip'), ('bca_oneklik', 'BCA OneKlik'), ('bri_oneklik', 'BRI OneKlik')], max_length=50)),
                ('subtotal', models.BigIntegerField()),
                ('shipping_fee', models.BigIntegerField(default=10000)),
                ('service_fee', models.BigIntegerField(default=3000)),
                ('total', models.BigIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variant', models.CharField(blank=True, default='', max_length=255)),
                ('price_at_purchase', models.BigIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('merchandise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cartApp.merchandise')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cartApp.order')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, max_length=64, null=True)),
                ('variant', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('selected', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('merchandise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartApp.merchandise')),
            ],
            options={
                'unique_together': {('session_key', 'merchandise', 'variant'), ('user', 'merchandise', 'variant')},
            },
        ),
    ]
