# Generated by Django 5.2.7 on 2025-10-24 01:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartApp', '0001_initial'),
        ('merchandiseApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('product_price', models.IntegerField(default=0)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='merchandiseApp.merchandise')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['user', 'product'], name='cartApp_pur_user_id_e86da6_idx'), models.Index(fields=['product'], name='cartApp_pur_product_73840e_idx'), models.Index(fields=['order_token'], name='cartApp_pur_order_t_9a33a3_idx')],
            },
        ),
    ]
