# Generated by Django 5.2.7 on 2025-10-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartApp', '0002_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='product_thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
