# Generated by Django 5.2.7 on 2025-10-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favoritesApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchandise',
            name='category',
        ),
        migrations.RemoveField(
            model_name='merchandise',
            name='user',
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
