# Generated by Django 5.2.7 on 2025-10-23 04:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('training jersey', 'Training Jersey'), ('tops', 'Tops'), ('jacket', 'Jacket'), ('hoodie', 'Hoodie'), ('sweatshirt', 'Sweatshirt'), ('vest', 'Vest'), ('socks', 'Socks'), ('ball', 'Ball'), ('bag', 'Bag'), ('tumbler', 'Tumbler'), ('action figure', 'Action Figure'), ('accessories', 'Accessories'), ('others', 'Others')], max_length=100)),
                ('stock', models.IntegerField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('product_views', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
